# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d79b5f6aa330e1dfeea99ab002fffcd52a2b464db24a4776034ad1d6c61db1cfeb570da42abe0fc3581bdddd1f6a0461ed1778418243cd4301fff6bd58d38e3e

test:
  secret_key_base: 591345f9f4e6d1a35a98f5c06d7160a0ec35e4ef6bb89f5c2a689ee6ec360a48dc15e3a66b17074573c9012bcd1ae14282c0230982e7214059d6e3ca996a99d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
